### PR TITLE
[ADD] Field Unit price

### PR DESCRIPTION
**Pull request by quentinDupont**
Require by HAL in Test#1 for v12 ;)
To be completed with grap/grap-odoo-custom#58 for GRAP custom views

index

### CODE REVIEW

**Comment by legalsylvain** [comment]
Hi  @quentinDupont. That's a great feature indeed. however, 
- I don't like the name "Unit Price", that is error prone IMO.
better to use "price per kilo" and "price per liter" instead ? 
could be an OCA module. 
- I think that the field(s) should be displayed only if set, AND if it is different than the sale price.

**Comment by quentinDupont** [comment]
> Hi @quentinDupont. That's a great feature indeed. however,
> 
>     * I don't like the name "Unit Price", that is error prone IMO.
>       better to use "price per kilo" and "price per liter" instead ?
>       could be an OCA module.
> 
>     * I think that the field(s) should be displayed only if set, AND if it is different than the sale price.

Unit price :arrow_right: Price per unit (generic name)
Only displayed if different or not null :heavy_check_mark:

**Comment by legalsylvain** [comment]
/ocabot merge patch

on est plus chaud que le climat.

**Comment by quentinDupont** [comment]
> /ocabot merge patch
> 
> on est plus chaud que le climat.

On est là on est là

**Comment by legalsylvain** [comment]
ouais, mais le bot, il a pas l'air d'être là, d'être là ;-)

**Comment by legalsylvain** [comment]
Guerrière, gros, 4h pour merger ! tu faisais la sieste ?

**Pull request merged**
